{
 "title": "Probe health",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "CPU (% of container capacity)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 *\nsum by (name) (\n  rate(container_cpu_usage_seconds_total{name=\"netpulse\"}[1m])\n)\n/\non(name) group_left()\nclamp_min(\n  max by (name) (\n    container_spec_cpu_quota{name=\"netpulse\"}\n  )\n  /\n  max by (name) (\n  container_spec_cpu_period{name=\"netpulse\"}\n  ),\n1\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QPS Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (target) (\n    rate(netpulse_requests_total[5m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\n  sum by (target) (\n    rate(netpulse_latency_seconds_count{status=\"success\"}[1m])\n  )\n  /\n  sum by (target) (\n    rate(netpulse_latency_seconds_count[1m])\n  )\n) * 100\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, \n  sum by (le, target) (\n    increase(netpulse_latency_seconds_bucket[5m])\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}